name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOTNET_WORKLOADS: maui-windows maui-android
  FRAMEWORK_VERSION: net9.0
  DOCKER_IMAGE: head-first-csharp-5-image

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} .
          docker images --filter=reference='${{ env.DOCKER_IMAGE }}'

  run-tests:
    name: Run Test
    needs: build-container
    strategy:
      matrix:
        config: [Debug, Release]
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/'${{ env.DOCKER_IMAGE }}':'${{ github.sha }}'
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: |
          dotnet --version
          dotnet workload list
      - name: Restore
        working-directory: Apps
        run: dotnet restore
      - name: Build
        working-directory: Apps
        run: dotnet build --no-restore --configuration ${{ matrix.config }} --framework ${{ env.FRAMEWORK_VERSION }}
      - name: Test
        working-directory: Apps
        run: dotnet test --no-restore --no-build --configuration ${{ matrix.config }} --framework ${{ env.FRAMEWORK_VERSION }} --verbosity normal
