name: Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  FRAMEWORK_VERSION: net9.0

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        config: [Debug, Release]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          echo ".NET version:"
          dotnet --version
          echo ".NET workload search:"
          dotnet workload search maui
          echo ".NET workload installation:"
          dotnet workload install maui-windows maui-android
          echo ".NET workload list:"
          dotnet workload list
      - name: Restore
        working-directory: Apps
        run: dotnet restore
      - name: Build
        working-directory: Apps
        run: dotnet build --no-restore --configuration ${{ matrix.config }} --framework ${{ env.FRAMEWORK_VERSION }}
      - name: Test
        working-directory: Apps
        run: dotnet test --no-restore --no-build --configuration ${{ matrix.config }} --framework ${{ env.FRAMEWORK_VERSION }} --verbosity normal
