name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOTNET_WORKLOADS: maui-windows maui-android
  FRAMEWORK_VERSION: net9.0

jobs:
  build-and-test:
    name: Build and Test
    strategy:
      matrix:
        config: [Debug, Release]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - uses: actions/checkout@v4
      - name: .NET Version
        run: dotnet --version
      - name: .NET Workloads
        run: |
          dotnet workload install ${{ env.DOTNET_WORKLOADS }}
          dotnet workload list 
          dotnet workload search
      - name: Restore
        working-directory: Apps
        run: dotnet restore
      - name: Build
        working-directory: Apps
        run: dotnet build --no-restore --configuration ${{ matrix.config }} --framework ${{ env.FRAMEWORK_VERSION }}
      - name: Test
        working-directory: Apps
        run: dotnet test --no-restore --no-build --configuration ${{ matrix.config }} --framework ${{ env.FRAMEWORK_VERSION }} --verbosity normal
