name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOTNET_VERSION: 9.0.x
  DOTNET_WORKLOADS: maui
  FRAMEWORK_VERSION: net9.0

jobs:
  build-and-test:
    name: Build and Test
    strategy:
      matrix:
        configuration: [Debug, Release]
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: dotnet --version
      # - name: Setup
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: ${{ env.DOTNET_VERSION }}
      # - name: .NET Workloads
      #   run: dotnet workload install ${{ env.DOTNET_WORKLOADS }}
      # - name: Restore
      #   working-directory: Apps
      #   run: dotnet restore
      # - name: Build
      #   working-directory: Apps
      #   run: dotnet build --no-restore --configuration ${{ matrix.configuration }} --framework ${{ env.FRAMEWORK_VERSION }}
      # - name: Test
      #   working-directory: Apps
      #   run: dotnet test --no-restore --no-build --configuration ${{ matrix.configuration }} --framework ${{ env.FRAMEWORK_VERSION }} --verbosity normal
