name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run_tests_debug_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: .NET Workloads
        run: dotnet workload install maui-windows maui-android
      - name: Restore
        working-directory: Apps
        run: dotnet restore
      - name: Build
        working-directory: Apps
        run: dotnet build --no-restore --configuration Debug --framework net9.0
      - name: Test
        working-directory: Apps
        run: dotnet test --no-restore --no-build --configuration Debug --framework net9.0 --verbosity normal

  run_tests_release_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: .NET Workloads
        run: dotnet workload install maui-windows maui-android
      - name: Restore
        working-directory: Apps
        run: dotnet restore
      - name: Build
        working-directory: Apps
        run: dotnet build --no-restore --configuration Release --framework net9.0
      - name: Test
        working-directory: Apps
        run: dotnet test --no-restore --no-build --configuration Release --framework net9.0 --verbosity normal
