name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOTNET_WORKLOADS: maui-windows maui-android
  FRAMEWORK_VERSION: net9.0

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build-and-test:
    name: Build and Test
    needs: build-container
    strategy:
      matrix:
        config: [Debug, Release]
    runs-on: ubuntu-latest
    container:
      image: ./Dockerfile
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: |
          dotnet --version
          dotnet workload list
      - name: Restore
        working-directory: Apps
        run: dotnet restore
      - name: Build
        working-directory: Apps
        run: dotnet build --no-restore --configuration ${{ matrix.config }} --framework ${{ env.FRAMEWORK_VERSION }}
      - name: Test
        working-directory: Apps
        run: dotnet test --no-restore --no-build --configuration ${{ matrix.config }} --framework ${{ env.FRAMEWORK_VERSION }} --verbosity normal
